apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fq.fullname" . }}-config
  labels:
    {{- include "fq.labels" . | nindent 4 }}
data:
  SCANNER_URL: {{ include "fq.scannerUrl" . | quote }}
  NEXTAUTH_URL: {{ printf "https://%s" .Values.ingress.host | quote }}
  NEXT_TELEMETRY_DISABLED: {{ .Values.web.env.NEXT_TELEMETRY_DISABLED | quote }}
  NODE_ENV: {{ .Values.web.env.NODE_ENV | quote }}
