apiVersion: v1
kind: Service
metadata:
  name: {{ include "fq.fullname" . }}-postgres
  labels:
    {{- include "fq.labels" . | nindent 4 }}
    {{- include "fq.postgres.selectorLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "fq.postgres.selectorLabels" . | nindent 4 }}
